server:
  port: 8080

init:
  datasource:
    url: jdbc:mysql://localhost:3306/?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: root
    database-name: demo_tower
spring:
  application:
    name: Simple-Demo
  datasource:
    url: jdbc:mysql://localhost:3306/demo_tower?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 600000
      maximum-pool-size: 10
      minimum-idle: 2
      auto-commit: false

    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl: ${REDIS_SSL:false}
      database: ${REDIS_DATABASE:0}
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms  # 获取连接最大等待时间
        shutdown-timeout: 100ms  # 关闭超时时间
mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名转换
